language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  - npm run build
  - cd dist && echo "registrasi.spartahmif.id" > CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master